services:
  - type: web
    name: ab-testing-demo
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/dependency/webapp-runner.jar --port $PORT target/*.war
    envVars:
      - key: JAVA_VERSION
        value: 11
